/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Contactos.Contactos;
/**
 *
 * @author Admin
 */
public class Interfaz extends javax.swing.JFrame {
    private Contactos[] contactosArray; //declaracion del atribudo del array de los contactos
    private int contadorContactos; //declaracion del atributo del contador de contactos

    
    public Interfaz() {
        initComponents();
        contactosArray = new Contactos[100];//defino el limite de contactos en 100
        contadorContactos = 0;//inicializo el contador
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textApellido = new javax.swing.JTextField();
        textNombre = new javax.swing.JTextField();
        textDni = new javax.swing.JTextField();
        direccionEtiqueta = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        textDireccion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        telefonoEtiqueta = new javax.swing.JLabel();
        textTelefono = new javax.swing.JTextField();
        fnacEtiqueta = new javax.swing.JLabel();
        dniEtiqueta = new javax.swing.JLabel();
        textFechaN = new javax.swing.JTextField();
        nombreEtiqueta = new javax.swing.JLabel();
        apellidoEtiqueta = new javax.swing.JLabel();
        tituloEtiqueta = new javax.swing.JLabel();
        textIndice = new javax.swing.JTextField();
        btnSiguiente = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(java.awt.SystemColor.controlLtHighlight);

        textNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNombreActionPerformed(evt);
            }
        });

        direccionEtiqueta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        direccionEtiqueta.setForeground(java.awt.SystemColor.textHighlight);
        direccionEtiqueta.setText("Direccion  :");

        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGuardar.setForeground(java.awt.SystemColor.textHighlight);
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jLabel1.setText("Indice:");

        telefonoEtiqueta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        telefonoEtiqueta.setForeground(java.awt.SystemColor.textHighlight);
        telefonoEtiqueta.setText("Telefono  :");

        fnacEtiqueta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        fnacEtiqueta.setForeground(java.awt.SystemColor.textHighlight);
        fnacEtiqueta.setText("F. Nac      :");

        dniEtiqueta.setBackground(new java.awt.Color(255, 255, 255));
        dniEtiqueta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dniEtiqueta.setForeground(java.awt.SystemColor.textHighlight);
        dniEtiqueta.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dniEtiqueta.setText("DNI            :");

        nombreEtiqueta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nombreEtiqueta.setForeground(java.awt.SystemColor.textHighlight);
        nombreEtiqueta.setText("Nombre    :");

        apellidoEtiqueta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        apellidoEtiqueta.setForeground(java.awt.SystemColor.textHighlight);
        apellidoEtiqueta.setText("Apellido :");

        tituloEtiqueta.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tituloEtiqueta.setForeground(java.awt.SystemColor.textHighlight);
        tituloEtiqueta.setText("AGENDA ELECTRONICA");

        textIndice.setEditable(false);
        textIndice.setText("0");
        textIndice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textIndiceActionPerformed(evt);
            }
        });

        btnSiguiente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSiguiente.setForeground(java.awt.SystemColor.textHighlight);
        btnSiguiente.setText(">>>");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        btnAnterior.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAnterior.setForeground(java.awt.SystemColor.textHighlight);
        btnAnterior.setText("<<<");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(direccionEtiqueta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dniEtiqueta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textDni)
                            .addComponent(textDireccion)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(nombreEtiqueta)
                        .addGap(19, 19, 19)
                        .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(telefonoEtiqueta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textTelefono))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(apellidoEtiqueta)
                        .addGap(18, 18, 18)
                        .addComponent(textApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(fnacEtiqueta)
                        .addGap(18, 18, 18)
                        .addComponent(textFechaN, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(103, 103, 103))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel1)
                        .addGap(29, 29, 29)
                        .addComponent(textIndice, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(btnAnterior)
                        .addGap(18, 18, 18)
                        .addComponent(btnGuardar)
                        .addGap(18, 18, 18)
                        .addComponent(btnSiguiente))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(tituloEtiqueta)))
                .addGap(69, 69, 69))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(tituloEtiqueta)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreEtiqueta)
                    .addComponent(apellidoEtiqueta)
                    .addComponent(textApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fnacEtiqueta)
                        .addComponent(textFechaN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dniEtiqueta)
                        .addComponent(textDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(direccionEtiqueta)
                    .addComponent(textDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefonoEtiqueta)
                    .addComponent(textTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnSiguiente)
                    .addComponent(btnAnterior))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textIndice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        
        //Guardado de la variable indice como string y conversion a int
        String indice = textIndice.getText(); 
        int ind;
        ind=Integer.parseInt(indice); 
        
        //recupero los datos ingresados
        String nombre = textNombre.getText();
        String apellido = textApellido.getText();
        String dni = textDni.getText();
        String direccion = textDireccion.getText();
        String fechaN = textFechaN.getText();
        String telefono= textTelefono.getText();
        
        //creo el objeto donde se guardaran los datos del contacto
        Contactos contacto=new Contactos();
        
        //guardo los datos recuperados anteriormente
        contacto.setIndice(ind);
        contacto.setNombre(nombre);
        contacto.setApellido(apellido);
        contacto.setDni(dni);
        contacto.setDireccion(direccion);
        contacto.setFechaN(fechaN);
        contacto.setTelefono(telefono);
        
        // Crea una nueva instancia de Contactos con los datos ingresados
        //es una variable de tipo "Contactos" porque va a guardar los objetos creados
        Contactos nuevoContacto = new Contactos();
        
        //se guarda el nuevo objeto
        nuevoContacto.setNombre(nombre);
        nuevoContacto.setApellido(apellido);
        nuevoContacto.setDni(dni);
        nuevoContacto.setDireccion(direccion);
        nuevoContacto.setFechaN(fechaN);
        nuevoContacto.setTelefono(telefono);
        
        // Agrega el nuevo contacto al arreglo
        if (contadorContactos < contactosArray.length) {
            contactosArray[contadorContactos] = contacto;
            contadorContactos++;
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void textNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNombreActionPerformed

        
    }//GEN-LAST:event_textNombreActionPerformed

    private void textIndiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textIndiceActionPerformed
        
    }//GEN-LAST:event_textIndiceActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        
        //guardadado de la variable indice y conversion a int
        //cambia el numero de indice cuando aprieta el boton
        int ind;
        String indice = textIndice.getText();
        ind=Integer.parseInt(indice);
        ind ++;
        indice = String.valueOf(ind);
        textIndice.setText(indice);
        
        //si el indice es menor al contador de contactos
        //se mostrara el contacto
        if (ind < contadorContactos) {
            Contactos contacto = contactosArray[ind];
            textNombre.setText(contacto.getNombre());
            textApellido.setText(contacto.getApellido());
            textDireccion.setText(contacto.getDireccion());
            textDni.setText(contacto.getDni());
            textFechaN.setText(contacto.getFechaN());
            textTelefono.setText(contacto.getTelefono());
        
            //si el indice es mayor a la cantida de contactos se pondra en blanco
        }else{
            textNombre.setText("");
            textApellido.setText("");
            textDireccion.setText("");
            textDni.setText("");
            textFechaN.setText("");
            textTelefono.setText("");
        }
            
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        
        //recupera indice y lo convierte
      
        int ind;
        String indice = textIndice.getText();
        ind=Integer.parseInt(indice);
        
        //si el indice es mayor a cero cuando presione el boton el indice bajara
        if (ind > 0) {
            ind --;
            indice = String.valueOf(ind);
            textIndice.setText(indice);
        }else{
            //si no no pasara nada
        }
          
        if (ind < contadorContactos) {
            Contactos contacto = contactosArray[ind];
            textNombre.setText(contacto.getNombre());
            textApellido.setText(contacto.getApellido());
            textDireccion.setText(contacto.getDireccion());
            textDni.setText(contacto.getDni());
            textFechaN.setText(contacto.getFechaN());
            textTelefono.setText(contacto.getTelefono());
            
        }else{
            textNombre.setText("");
            textApellido.setText("");
            textDireccion.setText("");
            textDni.setText("");
            textFechaN.setText("");
            textTelefono.setText("");
        }
    }//GEN-LAST:event_btnAnteriorActionPerformed

    /**
     * @param args the command line arguments
     */
    
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apellidoEtiqueta;
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JLabel direccionEtiqueta;
    private javax.swing.JLabel dniEtiqueta;
    private javax.swing.JLabel fnacEtiqueta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nombreEtiqueta;
    private javax.swing.JLabel telefonoEtiqueta;
    private javax.swing.JTextField textApellido;
    private javax.swing.JTextField textDireccion;
    private javax.swing.JTextField textDni;
    private javax.swing.JTextField textFechaN;
    private javax.swing.JTextField textIndice;
    private javax.swing.JTextField textNombre;
    private javax.swing.JTextField textTelefono;
    private javax.swing.JLabel tituloEtiqueta;
    // End of variables declaration//GEN-END:variables
}
